title: Hugo Barnes
description: >-
  The personal website of Hugo Barnes
baseurl: ""
domain: "hugobarnes.github.io"
url: "https://hugobarnes.github.io"
github_username:  Hugo Barnes
show_excerpts: true
markdown: kramdown
remote_theme: jekyll/minima@8cdd1fe

author:
  name: "Hugo Barnes"
  email: hugo.s.barnes@gmail.com

header_pages:
  - academic-notes.md
  - research.md
  - projects.md

permalink_old: /:categories/:year/:title:output_ext
permalink: /:categories/:year/:title

# Build settings
theme: minima
plugins:
  #- jekyll-feed
  - jekyll-remote-theme

exclude:
  - README.md
  - test.sh
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

minima:
  skin: tom
  social_links:
    github:  HugoBarnes
    linkedin: hugo-barnes

nav:
  - name: "Calvin and Hobbes Reader"
    link: "projects/candh/index.md"
  - name: "Scrabble Solver"
    link: "projects/scrabble/index.html"
  - name: "Sudoku"
    link: "projects/sudoku/index.html"

